# base docker-compose which is set to production

version: "3.8"
services:
  api:
    build: .
    image: ingredientory:latest
    container_name: ingredientory_api
    environment: 
      NODE_ENV: production
    ports:
      - "8080:8080"
