# base docker-compose

version: '3.8'
services:
  api:
    build: .
    image: 'ingredientory_api:latest'
    container_name: 'ingredientory_api'
    environment: 
      NODE_ENV: 'production'
    ports:
      - '8080:8080'
  db:
    image: 'mongo:bionic'
    container_name: 'mongo'
    # TODO: volumes
    